# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 8) do

  create_table "hats", :force => true do |t|
    t.column "style",   :string
    t.column "user_id", :integer
  end

  create_table "parties", :force => true do |t|
    t.column "name", :string
  end

  create_table "parties_people", :id => false, :force => true do |t|
    t.column "party_id",  :integer
    t.column "person_id", :integer
  end

  create_table "people", :force => true do |t|
    t.column "name", :string
    t.column "age",  :integer
  end

  create_table "posts", :force => true do |t|
    t.column "title", :string
    t.column "body",  :text
  end

  create_table "properties", :force => true do |t|
    t.column "thing_id", :integer
    t.column "name",     :string
  end

  create_table "things", :force => true do |t|
    t.column "name",      :string
    t.column "awesome",   :boolean
    t.column "person_id", :integer
    t.column "user_id",   :integer
  end

  create_table "users", :force => true do |t|
    t.column "email",      :string
    t.column "password",   :string
    t.column "first_name", :string
    t.column "last_name",  :string
  end

end
